# Generated by Django 5.2.7 on 2025-11-17 12:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0006_acgroupmaster_alter_subaccount_options_acgroup"),
        ("core", "0004_colourmaster_labmaster_sizemaster"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RepairIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tag_no", models.TextField(blank=True, null=True)),
                ("piece", models.IntegerField(blank=True, null=True)),
                ("remark", models.TextField(blank=True, null=True)),
                (
                    "gr_wt",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
                ),
                (
                    "net_wt",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
                ),
                (
                    "tunch",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
                ),
                (
                    "wstg",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
                ),
                (
                    "rate",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "total",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repair_issues",
                        to="accounts.account",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repair_issues",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_repair_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repair_issues",
                        to="core.itemnamemaster",
                    ),
                ),
                (
                    "stamp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repair_issues",
                        to="core.stampmaster",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_repair_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "repair_issues",
                "ordering": ["-created_at"],
            },
        ),
    ]
