# Generated by Django 5.2.7 on 2025-12-03 18:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_acgroupmaster_alter_subaccount_options_acgroup"),
        ("core", "0004_colourmaster_labmaster_sizemaster"),
        ("issues", "0001_initial"),
        ("vouchers", "0021_order_line_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("order_ref", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_issues",
                        to="accounts.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_order_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_issues",
                        to="core.itemnamemaster",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_issues",
                        to="vouchers.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Issue",
                "verbose_name_plural": "Order Issues",
                "db_table": "order_issues",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="order_issue_created_b540fe_idx"),
                    models.Index(fields=["status"], name="order_issue_status_d9065a_idx"),
                    models.Index(fields=["order"], name="order_issue_order_i_aa614a_idx"),
                ],
            },
        ),
    ]
