# Generated by Django 5.2.7 on 2025-12-08 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_acgroupmaster_alter_subaccount_options_acgroup"),
        ("core", "0004_colourmaster_labmaster_sizemaster"),
        ("issues", "0002_orderissue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("gold_carat", models.CharField(max_length=50)),
                ("gender", models.CharField(blank=True, max_length=50, null=True)),
                ("size", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("delivery_type", models.CharField(blank=True, max_length=100, null=True)),
                ("query_in_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "reference_image",
                    models.FileField(blank=True, null=True, upload_to="query_references/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("converted_to_order", "Converted to Order"),
                            ("archived", "Archived"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queries",
                        to="accounts.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="queries",
                        to="core.itemnamemaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Query",
                "verbose_name_plural": "Queries",
                "db_table": "queries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="queries_created_e3ce76_idx"),
                    models.Index(fields=["status"], name="queries_status_f25a76_idx"),
                    models.Index(fields=["account"], name="queries_account_ea3b00_idx"),
                    models.Index(fields=["expiry_date"], name="queries_expiry__cd5fa0_idx"),
                ],
            },
        ),
    ]
