# Generated by Django 5.2.7 on 2025-12-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0003_query"),
    ]

    operations = [
        migrations.AddField(
            model_name="query",
            name="item_name_custom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="query",
            name="subaccount",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
