# Generated by Django 5.2.7 on 2025-11-07 12:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseMetalMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_metals",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "base_metal_master",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SeriesMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "series_master",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StampMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stamps",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "stamp_master",
                "ordering": ["name"],
            },
        ),
    ]
