# Generated by Django 5.2.7 on 2025-11-07 13:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_basemetalmaster_seriesmaster_stampmaster"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClarityMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clarities",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "clarity_master",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ItemNameMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_names",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "item_name_master",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ShapeMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shapes",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "shape_master",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UnitMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "unit_master",
                "ordering": ["name"],
            },
        ),
    ]
