# Generated by Django 5.2.7 on 2025-11-11 14:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_claritymaster_itemnamemaster_shapemaster_unitmaster"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColourMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colours",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "colour_master",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LabMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labs",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "lab_master",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SizeMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "size_master",
                "ordering": ["name"],
            },
        ),
    ]
