# Generated by Django 5.2.7 on 2026-01-09 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_colourmaster_labmaster_sizemaster"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterDataRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "master_type",
                    models.CharField(
                        choices=[
                            ("item_name", "Item Name"),
                            ("gold_carat", "Gold Carat"),
                            ("metal_type", "Metal Type"),
                            ("metal_color", "Metal Color"),
                            ("clarity", "Clarity"),
                            ("shape", "Shape"),
                            ("colour", "Colour"),
                            ("size", "Size"),
                            ("unit", "Unit"),
                            ("lab", "Lab"),
                        ],
                        max_length=50,
                    ),
                ),
                ("requested_value", models.CharField(max_length=200)),
                ("additional_info", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="master_requests",
                        to="core.company",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="master_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_master_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "master_data_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MetalTypeMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metal_types",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "metal_type_master",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MetalColorMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metal_colors",
                        to="core.company",
                    ),
                ),
                (
                    "metal_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colors",
                        to="core.metaltypemaster",
                    ),
                ),
            ],
            options={
                "db_table": "metal_color_master",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GoldCaratMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("value", models.IntegerField()),
                ("is_standard", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gold_carats",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "gold_carat_master",
                "ordering": ["-value"],
                "unique_together": {("company", "value")},
            },
        ),
    ]
