# Generated by Django 5.2.7 on 2026-01-10 09:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_add_master_data_management"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterdatarequest",
            name="master_type",
            field=models.CharField(
                choices=[
                    ("item_name", "Item Name"),
                    ("gold_carat", "Gold Carat"),
                    ("metal_type", "Metal Type"),
                    ("metal_color", "Metal Color"),
                    ("item_group", "Item Group"),
                    ("clarity", "Clarity"),
                    ("shape", "Shape"),
                    ("colour", "Colour"),
                    ("size", "Size"),
                    ("unit", "Unit"),
                    ("lab", "Lab"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ItemGroupMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_groups",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "item_group_master",
                "ordering": ["name"],
            },
        ),
    ]
