# Generated by Django 5.2.7 on 2026-01-27 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_add_gemstone_masters"),
        ("core", "0006_add_item_group_master"),
    ]

    operations = []
