# Generated by Django 5.0.14 on 2026-01-29 15:41

from django.db import migrations


def add_material_types(apps, schema_editor):
    """Add Diamond and Gemstone to MetalTypeMaster"""
    MetalTypeMaster = apps.get_model("core", "MetalTypeMaster")

    # Create material types if they don't exist
    material_types = ["Diamond", "Gemstone"]

    for material_type in material_types:
        MetalTypeMaster.objects.get_or_create(
            name=material_type,
            company=None,  # Global material types
        )


def remove_material_types(apps, schema_editor):
    """Remove Diamond and Gemstone from MetalTypeMaster"""
    MetalTypeMaster = apps.get_model("core", "MetalTypeMaster")
    MetalTypeMaster.objects.filter(name__in=["Diamond", "Gemstone"], company__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_merge_20260127_1656"),
    ]

    operations = [
        migrations.RunPython(add_material_types, remove_material_types),
    ]
