# Generated by Django 5.0.14 on 2026-01-29 17:32

from django.db import migrations


def add_diamond_shapes(apps, schema_editor):
    """Add default diamond shapes"""
    ShapeMaster = apps.get_model("core", "ShapeMaster")

    # Diamond shapes from the specification
    shapes = [
        "Round",
        "Princess",
        "Cushion",
        "Emerald",
        "Oval",
        "Radiant",
        "Asscher",
        "Marquise",
        "Heart",
        "Pear",
        "Baguette",
    ]

    for shape_name in shapes:
        ShapeMaster.objects.get_or_create(
            name=shape_name,
            company=None,  # Global shapes
        )


def remove_diamond_shapes(apps, schema_editor):
    """Remove default diamond shapes"""
    ShapeMaster = apps.get_model("core", "ShapeMaster")
    shapes = [
        "Round",
        "Princess",
        "Cushion",
        "Emerald",
        "Oval",
        "Radiant",
        "Asscher",
        "Marquise",
        "Heart",
        "Pear",
        "Baguette",
    ]
    ShapeMaster.objects.filter(name__in=shapes, company__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_add_diamond_gemstone_material_types"),
    ]

    operations = [
        migrations.RunPython(add_diamond_shapes, remove_diamond_shapes),
    ]
