# Generated by Django 5.0.14 on 2026-02-01 19:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_add_default_diamond_shapes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoldPriceFeeding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gold_24k_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="24 Karat gold rate per gram in INR",
                        max_digits=10,
                    ),
                ),
                (
                    "gold_22k_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="22 Karat gold rate per gram in INR",
                        max_digits=10,
                    ),
                ),
                (
                    "silver_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Silver rate per gram in INR",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "update_type",
                    models.CharField(
                        choices=[
                            ("OPENING", "Opening (12 PM)"),
                            ("CLOSING", "Closing (Before 10 PM)"),
                        ],
                        default="OPENING",
                        max_length=10,
                    ),
                ),
                (
                    "feeding_date",
                    models.DateField(help_text="Date for which this rate is applicable"),
                ),
                ("fed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes about the rate", null=True
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gold_prices",
                        to="core.company",
                    ),
                ),
                (
                    "fed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gold_price_feedings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gold_price_feeding",
                "ordering": ["-feeding_date", "-fed_at"],
                "indexes": [
                    models.Index(
                        fields=["feeding_date", "update_type"],
                        name="gold_price__feeding_b83781_idx",
                    ),
                    models.Index(
                        fields=["company", "feeding_date"],
                        name="gold_price__company_1b7cf6_idx",
                    ),
                ],
                "unique_together": {("company", "feeding_date", "update_type")},
            },
        ),
    ]
