# Generated by Django 5.0.14 on 2026-02-01 20:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_add_gold_price_feeding"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("ACCOUNTS", "Accounts"),
                            ("PRODUCTION", "Production"),
                            ("RAW_MATERIAL", "Raw Material Inventory"),
                            ("ADMINISTRATION", "Administration"),
                            ("LOGISTICS", "Logistics"),
                            ("SALES", "Sales/Query"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "features",
                    models.JSONField(
                        default=list,
                        help_text="List of features/widgets to show on dashboard",
                    ),
                ),
                ("can_edit_gold_price", models.BooleanField(default=False)),
                ("can_view_accounting", models.BooleanField(default=False)),
                ("can_view_production", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "departments",
                "ordering": ["name"],
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="DashboardConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "widgets",
                    models.JSONField(
                        default=list,
                        help_text="List of widgets to display with their settings",
                    ),
                ),
                (
                    "layout_type",
                    models.CharField(
                        choices=[
                            ("GRID", "Grid Layout"),
                            ("LIST", "List Layout"),
                            ("CUSTOM", "Custom Layout"),
                        ],
                        default="GRID",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_config",
                        to="core.department",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_configurations",
            },
        ),
    ]
