# Generated by Django 5.0.14 on 2026-02-01 20:16

from django.db import migrations


def populate_departments(apps, schema_editor):
    """Create initial departments"""
    Department = apps.get_model("core", "Department")
    DashboardConfiguration = apps.get_model("core", "DashboardConfiguration")

    departments_data = [
        {
            "name": "Accounts",
            "code": "ACCOUNTS",
            "description": "Accounting and Finance Department",
            "can_edit_gold_price": True,
            "can_view_accounting": True,
            "features": ["gold_price", "invoices", "payments", "tally"],
            "widgets": [
                {"type": "gold_price", "position": 1, "size": "large"},
                {"type": "pending_tasks", "position": 2, "size": "large"},
                {"type": "pending_invoices", "position": 3, "size": "medium"},
                {"type": "advance_payments", "position": 4, "size": "medium"},
            ],
        },
        {
            "name": "Production",
            "code": "PRODUCTION",
            "description": "Production and Manufacturing Department",
            "can_view_production": True,
            "features": ["tasks", "workflow", "material_tracking"],
            "widgets": [
                {"type": "pending_tasks", "position": 1, "size": "large"},
                {"type": "production_workflow", "position": 2, "size": "large"},
                {"type": "gold_price_readonly", "position": 3, "size": "small"},
            ],
        },
        {
            "name": "Raw Material Inventory",
            "code": "RAW_MATERIAL",
            "description": "Raw Material Inventory Management",
            "features": ["tasks", "inventory", "purchases"],
            "widgets": [
                {"type": "pending_tasks", "position": 1, "size": "large"},
                {"type": "inventory_summary", "position": 2, "size": "medium"},
                {"type": "purchase_orders", "position": 3, "size": "medium"},
            ],
        },
        {
            "name": "Administration",
            "code": "ADMINISTRATION",
            "description": "Administration and ERP Management",
            "features": ["tasks", "staff", "documents"],
            "widgets": [
                {"type": "pending_tasks", "position": 1, "size": "large"},
                {"type": "staff_management", "position": 2, "size": "medium"},
            ],
        },
        {
            "name": "Logistics",
            "code": "LOGISTICS",
            "description": "Logistics and Shipping Department",
            "features": ["tasks", "shipments", "delivery"],
            "widgets": [
                {"type": "pending_tasks", "position": 1, "size": "large"},
                {"type": "shipment_tracking", "position": 2, "size": "medium"},
            ],
        },
        {
            "name": "Sales/Query",
            "code": "SALES",
            "description": "Sales and Customer Query Management",
            "features": ["tasks", "queries", "estimates"],
            "widgets": [
                {"type": "pending_tasks", "position": 1, "size": "large"},
                {"type": "active_queries", "position": 2, "size": "medium"},
                {"type": "pending_estimates", "position": 3, "size": "medium"},
            ],
        },
    ]

    for dept_data in departments_data:
        widgets = dept_data.pop("widgets")
        dept, created = Department.objects.get_or_create(code=dept_data["code"], defaults=dept_data)

        if created:
            # Create dashboard configuration
            DashboardConfiguration.objects.create(
                department=dept, widgets=widgets, layout_type="GRID"
            )


def remove_departments(apps, schema_editor):
    """Remove initial departments"""
    Department = apps.get_model("core", "Department")
    Department.objects.filter(
        code__in=["ACCOUNTS", "PRODUCTION", "RAW_MATERIAL", "ADMINISTRATION", "LOGISTICS", "SALES"]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_add_department_models"),
    ]

    operations = [
        migrations.RunPython(populate_departments, remove_departments),
    ]
