# Generated by Django 5.0.14 on 2026-02-08 14:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_populate_initial_departments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyGoldRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rate_date", models.DateField(db_index=True)),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("OPENING", "Opening Rate"),
                            ("INTERMEDIATE", "Intermediate Rate"),
                            ("CLOSING", "Closing Rate"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "gold_24k_999",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="24K Triple 9 (999) gold rate per gram",
                        max_digits=10,
                    ),
                ),
                (
                    "gold_24k_995",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="24K 995 gold rate per gram",
                        max_digits=10,
                    ),
                ),
                (
                    "gold_22k",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="22K gold rate (0.912 × 24K 999)",
                        max_digits=10,
                    ),
                ),
                (
                    "gold_18k",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="18K gold rate (0.75 × 24K 999)",
                        max_digits=10,
                    ),
                ),
                (
                    "gold_14k",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="14K gold rate (0.6 × 24K 999)",
                        max_digits=10,
                    ),
                ),
                (
                    "silver_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Silver rate per gram",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Once locked, rate cannot be changed (except by admin override)",
                    ),
                ),
                ("entered_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified_at", models.DateTimeField(blank=True, null=True)),
                ("correction_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gold_rates",
                        to="core.company",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entered_gold_rates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_gold_rates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "daily_gold_rates",
                "ordering": ["-rate_date", "entered_at"],
            },
        ),
        migrations.CreateModel(
            name="GoldRateChangeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("LOCK", "Locked"),
                            ("OVERRIDE", "Admin Override"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "field_changed",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("old_value", models.CharField(blank=True, max_length=255, null=True)),
                ("new_value", models.CharField(blank=True, max_length=255, null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gold_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="core.dailygoldrate",
                    ),
                ),
            ],
            options={
                "db_table": "gold_rate_change_logs",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dailygoldrate",
            index=models.Index(
                fields=["company", "rate_date", "rate_type"],
                name="daily_gold__company_eb1406_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dailygoldrate",
            index=models.Index(
                fields=["rate_date", "rate_type"], name="daily_gold__rate_da_eb0fda_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailygoldrate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("rate_type__in", ["OPENING", "CLOSING"])),
                fields=("company", "rate_date", "rate_type"),
                name="unique_opening_closing_per_day",
            ),
        ),
    ]
