# Generated by Django 5.0.14 on 2026-02-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_add_gold_rate_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailygoldrate",
            name="gold_22k",
            field=models.DecimalField(
                decimal_places=2,
                help_text="22K gold rate (0.91 × 24K 999)",
                max_digits=10,
            ),
        ),
    ]
