# Generated by Django 5.2.7 on 2025-11-03 18:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("account_no", models.TextField()),
                ("account_name", models.TextField()),
                (
                    "group_code",
                    models.CharField(
                        choices=[
                            ("CUSTOMER", "Customer"),
                            ("SUPPLIER", "Supplier"),
                            ("AGENT", "Agent"),
                            ("STAFF", "Staff"),
                        ],
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounts",
                        to="core.branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "accounts",
                "ordering": ["account_name"],
            },
        ),
        migrations.CreateModel(
            name="AccountBank",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="bank",
                        serialize=False,
                        to="accounts.account",
                    ),
                ),
                ("bank_name", models.TextField(blank=True, null=True)),
                ("branch", models.TextField(blank=True, null=True)),
                ("ifsc", models.TextField(blank=True, null=True)),
                ("account_number", models.TextField(blank=True, null=True)),
                ("upi_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "account_bank",
            },
        ),
        migrations.CreateModel(
            name="AccountContact",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="contact",
                        serialize=False,
                        to="accounts.account",
                    ),
                ),
                ("address_line", models.TextField()),
                ("pin_code", models.TextField(blank=True, null=True)),
                ("phone", models.TextField(blank=True, null=True)),
                ("mobile_ccode", models.TextField(blank=True, null=True)),
                ("mobile", models.TextField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "account_contact",
            },
        ),
        migrations.CreateModel(
            name="AccountOpeningBalance",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="opening_balance",
                        serialize=False,
                        to="accounts.account",
                    ),
                ),
                ("balance_date", models.DateField(blank=True, null=True)),
                (
                    "gold_fine",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "gold_drcr",
                    models.CharField(
                        blank=True,
                        choices=[("Dr", "Debit"), ("Cr", "Credit")],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "silver_fine",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "silver_drcr",
                    models.CharField(
                        blank=True,
                        choices=[("Dr", "Debit"), ("Cr", "Credit")],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "amount_drcr",
                    models.CharField(
                        blank=True,
                        choices=[("Dr", "Debit"), ("Cr", "Credit")],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "profit_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
            ],
            options={
                "db_table": "account_opening_balance",
            },
        ),
        migrations.CreateModel(
            name="AccountTax",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="tax",
                        serialize=False,
                        to="accounts.account",
                    ),
                ),
                ("gstin", models.TextField(blank=True, null=True)),
                ("pan", models.TextField(blank=True, null=True)),
                ("tan", models.TextField(blank=True, null=True)),
                (
                    "tcs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "tds",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("hm_no", models.TextField(blank=True, null=True)),
                ("cst_no", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "account_tax",
            },
        ),
    ]
