# Generated by Django 5.2.7 on 2025-11-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountcontact",
            name="city",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accountcontact",
            name="country",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accountcontact",
            name="state",
            field=models.TextField(blank=True, null=True),
        ),
    ]
