# Generated by Django 5.2.7 on 2025-11-07 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_accountcontact_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountbank",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="accountbank",
            name="upi_id",
        ),
        migrations.RemoveField(
            model_name="accountcontact",
            name="mobile",
        ),
        migrations.RemoveField(
            model_name="accountcontact",
            name="mobile_ccode",
        ),
        migrations.RemoveField(
            model_name="accountopeningbalance",
            name="balance_date",
        ),
        migrations.RemoveField(
            model_name="accountopeningbalance",
            name="gold_drcr",
        ),
        migrations.RemoveField(
            model_name="accountopeningbalance",
            name="gold_fine",
        ),
        migrations.RemoveField(
            model_name="accountopeningbalance",
            name="profit_pct",
        ),
        migrations.RemoveField(
            model_name="accountopeningbalance",
            name="silver_drcr",
        ),
        migrations.RemoveField(
            model_name="accountopeningbalance",
            name="silver_fine",
        ),
        migrations.RemoveField(
            model_name="accounttax",
            name="cst_no",
        ),
        migrations.RemoveField(
            model_name="accounttax",
            name="hm_no",
        ),
        migrations.RemoveField(
            model_name="accounttax",
            name="tan",
        ),
        migrations.RemoveField(
            model_name="accounttax",
            name="tcs",
        ),
        migrations.RemoveField(
            model_name="accounttax",
            name="tds",
        ),
    ]
