# Generated by Django 5.2.7 on 2025-11-10 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_accountbank_branch_remove_accountbank_upi_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sub_account_name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=50, null=True)),
                ("ring_size", models.CharField(blank=True, max_length=50, null=True)),
                ("bangle_size", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("MALE", "Male"), ("FEMALE", "Female"), ("OTHERS", "Others")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("item_name", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_accounts",
                        to="accounts.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_subaccounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub Account",
                "verbose_name_plural": "Sub Accounts",
                "db_table": "sub_accounts",
                "ordering": ["-created_at"],
            },
        ),
    ]
