# Generated by Django 5.2.7 on 2025-11-11 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_subaccount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ACGroupMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "ac_group_master",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="subaccount",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Sub Accounts",
                "verbose_name_plural": "Sub Accounts",
            },
        ),
        migrations.CreateModel(
            name="ACGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "incl_in_sale",
                    models.CharField(
                        choices=[("YES", "YES"), ("NO", "NO")], default="NO", max_length=3
                    ),
                ),
                (
                    "incl_in_pur",
                    models.CharField(
                        choices=[("YES", "YES"), ("NO", "NO")], default="NO", max_length=3
                    ),
                ),
                (
                    "incl_in_out",
                    models.CharField(
                        choices=[("YES", "YES"), ("NO", "NO")], default="NO", max_length=3
                    ),
                ),
                (
                    "incl_in_ir",
                    models.CharField(
                        choices=[("YES", "YES"), ("NO", "NO")], default="NO", max_length=3
                    ),
                ),
                (
                    "address_req",
                    models.CharField(
                        choices=[("YES", "YES"), ("NO", "NO")], default="NO", max_length=3
                    ),
                ),
                (
                    "restrict_credit_facility",
                    models.CharField(
                        choices=[("YES", "YES"), ("NO", "NO")], default="NO", max_length=3
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_acgroups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ac_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ac_groups",
                        to="accounts.acgroupmaster",
                    ),
                ),
            ],
            options={
                "db_table": "ac_groups",
                "ordering": ["-created_at"],
            },
        ),
    ]
