# Generated by Django 5.2.7 on 2026-01-09 16:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_restructure_subaccount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subaccount",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Sub Account",
                "verbose_name_plural": "Sub Accounts",
            },
        ),
    ]
