# Generated by Django 5.2.7 on 2025-11-07 08:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
        ("core", "0001_initial"),
        ("vouchers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="Voucher",
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        blank=True,
                        choices=[("DEFAULT", "Default"), ("S1", "S1"), ("S2", "S2")],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("bill_no", models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ("item_name", models.TextField(blank=True, null=True)),
                ("design", models.TextField(blank=True, null=True)),
                ("job_no", models.CharField(blank=True, max_length=64, null=True, unique=True)),
                (
                    "stamp",
                    models.CharField(
                        blank=True,
                        choices=[("", "None"), ("22K", "22K"), ("18K", "18K")],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("gold_rate", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "base_metal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YELLOW_GOLD", "Yellow Gold"),
                            ("WHITE_GOLD", "White Gold"),
                            ("ROSE_GOLD", "Rose Gold"),
                            ("SILVER_ALLOY", "Silver Alloy"),
                            ("PLATINUM", "Platinum"),
                            ("TITANIUM", "Titanium"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "rhodium_instruction",
                    models.CharField(
                        blank=True,
                        choices=[("", "None"), ("LIGHT", "Light"), ("HEAVY", "Heavy")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "number_of_pieces",
                    models.IntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "estimated_gross_weight",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "estimated_gold_weight",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "estimated_diamond_weight",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("tunch_percent", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                (
                    "average_diamond_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "gemstone_stone_weight",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "craftsmanship_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "advance_payment_received",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=14, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vouchers",
                        to="accounts.account",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vouchers",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vouchers",
                "ordering": ["-created_at"],
            },
        ),
    ]
