# Generated by Django 5.2.7 on 2025-11-07 08:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
        ("core", "0001_initial"),
        ("vouchers", "0002_order_delete_voucher"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="rhodium_instruction",
        ),
        migrations.AlterField(
            model_name="order",
            name="advance_payment_received",
            field=models.CharField(
                blank=True,
                choices=[("YES", "Yes"), ("NO", "No")],
                default="NO",
                max_length=3,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tag_no", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "item_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("14K Gold Misc", "14K Gold Misc"),
                            ("AMYTHYST", "AMYTHYST"),
                            ("BALI (Earrings)", "BALI (Earrings)"),
                            ("BANGLE", "BANGLE"),
                            ("BRACELET", "BRACELET"),
                            ("BROACH", "BROACH"),
                            ("DIAMOND", "DIAMOND"),
                            ("GOLD CHAIN", "GOLD CHAIN"),
                            ("GOLD BRACELET", "GOLD BRACELET"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "shape",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ASHER", "ASHER"),
                            ("BUGGET", "BUGGET"),
                            ("CUSHION", "CUSHION"),
                            ("EMERALD", "EMERALD"),
                            ("HEART", "HEART"),
                            ("OVAL", "OVAL"),
                            ("ROSE CUT", "ROSE CUT"),
                            ("RADIANT", "RADIANT"),
                            ("TAPPER", "TAPPER"),
                            ("TRIANGLE", "TRIANGLE"),
                            ("TRILLION", "TRILLION"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "clarity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("I1", "I1"),
                            ("I2", "I2"),
                            ("I3", "I3"),
                            ("IF", "IF"),
                            ("SI", "SI"),
                            ("SI1", "SI1"),
                            ("SI2", "SI2"),
                            ("SI3", "SI3"),
                            ("VS-SI", "VS-SI"),
                            ("VS1", "VS1"),
                            ("VS2", "VS2"),
                            ("VVS", "VVS"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("order_no", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "stamp",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("14K", "14K"),
                            ("18K", "18K"),
                            ("22K", "22K"),
                            ("24K", "24K"),
                            ("9KT", "9KT"),
                            ("ROUND", "ROUND"),
                            ("SILVER", "SILVER"),
                        ],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("batch", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Carat", "Carat"),
                            ("Cent", "Cent"),
                            ("Gm", "Gm"),
                            ("Kg", "Kg"),
                            ("Pc", "Pc"),
                            ("Ratti", "Ratti"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("piece", models.IntegerField(blank=True, null=True)),
                (
                    "gr_wt",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
                ),
                (
                    "net_wt",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
                ),
                (
                    "rate",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to="accounts.account",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sales",
                "ordering": ["-created_at"],
            },
        ),
    ]
