# Generated by Django 5.2.7 on 2025-11-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0003_remove_order_rhodium_instruction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="base_metal",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="stamp",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
