# Generated by Django 5.2.7 on 2025-11-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0004_alter_order_base_metal_alter_order_stamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="clarity",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="item_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="shape",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="stamp",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="unit",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
