# Generated by Django 5.2.7 on 2025-11-11 14:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_acgroupmaster_alter_subaccount_options_acgroup"),
        ("core", "0004_colourmaster_labmaster_sizemaster"),
        ("vouchers", "0008_purandapprovalm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseDiamond",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("batch", models.CharField(blank=True, max_length=128, null=True)),
                ("piece", models.IntegerField(blank=True, null=True)),
                ("wt", models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                (
                    "less_percent",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
                ),
                (
                    "ex_rate",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                (
                    "inr_ct",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_diamond",
                        to="accounts.account",
                    ),
                ),
                (
                    "clarity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_diamond",
                        to="core.claritymaster",
                    ),
                ),
                (
                    "colour",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_diamond",
                        to="core.colourmaster",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_diamond",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_purchase_diamond",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_diamond",
                        to="core.itemnamemaster",
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_diamond",
                        to="core.labmaster",
                    ),
                ),
                (
                    "shape",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_diamond",
                        to="core.shapemaster",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_diamond",
                        to="core.sizemaster",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_purchase_diamond",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "purchase_diamond",
                "ordering": ["-created_at"],
            },
        ),
    ]
