# Generated by Django 5.2.7 on 2025-11-12 08:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_acgroupmaster_alter_subaccount_options_acgroup"),
        ("core", "0004_colourmaster_labmaster_sizemaster"),
        ("vouchers", "0009_purchasediamond"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Archives",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        blank=True,
                        choices=[("DEFAULT", "Default"), ("S1", "S1"), ("S2", "S2")],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("bill_no", models.CharField(blank=True, max_length=64, null=True)),
                ("item_name", models.TextField(blank=True, null=True)),
                ("design", models.TextField(blank=True, null=True)),
                ("job_no", models.CharField(blank=True, max_length=64, null=True)),
                ("stamp", models.CharField(blank=True, max_length=64, null=True)),
                ("gold_rate", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("base_metal", models.CharField(blank=True, max_length=64, null=True)),
                ("size", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "number_of_pieces",
                    models.IntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "estimated_gross_weight",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "estimated_gold_weight",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "estimated_diamond_weight",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("tunch_percent", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                (
                    "average_diamond_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "gemstone_stone_weight",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "craftsmanship_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "advance_payment_received",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Yes"), ("NO", "No")],
                        default="NO",
                        max_length=3,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archives",
                        to="accounts.account",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archives",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "archives",
                "ordering": ["-created_at"],
            },
        ),
    ]
