# Generated by Django 5.2.7 on 2025-11-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0010_archives"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="upload_file",
            field=models.FileField(blank=True, null=True, upload_to="order_uploads/"),
        ),
    ]
