# Generated by Django 5.2.7 on 2025-11-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0011_order_upload_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="archives",
            name="upload_file",
            field=models.FileField(blank=True, null=True, upload_to="order_uploads/"),
        ),
    ]
