# Generated by Django 5.2.7 on 2025-11-21 08:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_acgroupmaster_alter_subaccount_options_acgroup"),
        ("core", "0004_colourmaster_labmaster_sizemaster"),
        ("vouchers", "0016_journalentry_paymententry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tag_no", models.CharField(blank=True, max_length=128, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("order_no", models.CharField(blank=True, max_length=128, null=True)),
                ("remark", models.TextField(blank=True, null=True)),
                ("piece", models.IntegerField(blank=True, null=True)),
                (
                    "gr_wt",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
                ),
                (
                    "net_wt",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
                ),
                (
                    "divide",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
                ),
                (
                    "tunch",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
                ),
                (
                    "wstg",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
                ),
                (
                    "rate",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "mrp",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=256, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pur_returns",
                        to="accounts.account",
                    ),
                ),
                (
                    "clarity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pur_returns",
                        to="core.claritymaster",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pur_returns",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_pur_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pur_returns",
                        to="core.itemnamemaster",
                    ),
                ),
                (
                    "shape",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pur_returns",
                        to="core.shapemaster",
                    ),
                ),
                (
                    "stamp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pur_returns",
                        to="core.stampmaster",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pur_returns",
                        to="core.unitmaster",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_pur_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pur_return",
                "ordering": ["-created_at"],
            },
        ),
    ]
