"""Add new order line / weight fields to Order model

Generated by assistant to add optional fields used by the frontend Add Order form.
"""

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0020_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="item_name_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders_itemname",
                to="core.itemnamemaster",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="stamp_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders_stamp",
                to="core.stampmaster",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="size_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders_size",
                to="core.sizemaster",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="pc",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="wt",
            field=models.DecimalField(blank=True, null=True, max_digits=12, decimal_places=3),
        ),
        migrations.AddField(
            model_name="order",
            name="unit",
            field=models.DecimalField(blank=True, null=True, max_digits=12, decimal_places=3),
        ),
        migrations.AddField(
            model_name="order",
            name="rate_item",
            field=models.DecimalField(blank=True, null=True, max_digits=14, decimal_places=2),
        ),
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, null=True, blank=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="value_item",
            field=models.DecimalField(blank=True, null=True, max_digits=12, decimal_places=2),
        ),
    ]
