# Generated by Django 5.2.7 on 2025-12-10 17:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_acgroupmaster_alter_subaccount_options_acgroup"),
        ("core", "0004_colourmaster_labmaster_sizemaster"),
        ("vouchers", "0021_order_line_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EstimateVoucher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("item_name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("total_taxable_value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("gst_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("grand_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estimate_vouchers",
                        to="accounts.account",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimate_vouchers",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_estimates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_estimates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "estimate_vouchers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EstimateLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("particulars", models.CharField(max_length=255)),
                ("shape", models.CharField(blank=True, max_length=50)),
                ("colour", models.CharField(blank=True, max_length=50)),
                ("clarity", models.CharField(blank=True, max_length=50)),
                ("pc", models.IntegerField(blank=True, null=True)),
                (
                    "weight",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, choices=[("CT", "Carat"), ("GM", "Gram")], max_length=10
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("order", models.IntegerField(default=0)),
                (
                    "estimate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="vouchers.estimatevoucher",
                    ),
                ),
            ],
            options={
                "db_table": "estimate_line_items",
                "ordering": ["order"],
            },
        ),
    ]
