# Generated by Django 5.2.7 on 2025-12-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0022_estimatevoucher_estimatelineitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimatelineitem",
            name="is_compulsory",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="estimatelineitem",
            name="raw_material",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Diamond", "Diamond"),
                    ("Gemstone", "Gemstone"),
                    ("Gold", "Gold"),
                    ("Craftsmanship", "Craftsmanship Fee"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
