# Generated by Django 5.2.7 on 2026-01-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0023_add_raw_material_fields_to_estimate_line_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasediamond",
            name="proof_image",
            field=models.ImageField(blank=True, null=True, upload_to="purchase_proofs/"),
        ),
        migrations.AddField(
            model_name="purchasem",
            name="proof_image",
            field=models.ImageField(blank=True, null=True, upload_to="purchase_proofs/"),
        ),
        migrations.AddField(
            model_name="purchasetagwisem",
            name="proof_image",
            field=models.ImageField(blank=True, null=True, upload_to="purchase_proofs/"),
        ),
    ]
