# Generated by Django 5.2.7 on 2026-01-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0024_purchasediamond_proof_image_purchasem_proof_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymententry",
            name="proof_image",
            field=models.ImageField(blank=True, null=True, upload_to="payment_proofs/"),
        ),
    ]
