# Generated by Django 5.2.7 on 2026-01-07 09:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_colourmaster_labmaster_sizemaster"),
        ("vouchers", "0026_rawmaterialpurchase"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RawMaterialInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "available_carat",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("issued_carat", models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ("original_carat", models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("PARTIALLY_ISSUED", "Partially Issued"),
                            ("FULLY_ISSUED", "Fully Issued"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_material_inventory",
                        to="core.company",
                    ),
                ),
                (
                    "purchase",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_record",
                        to="vouchers.rawmaterialpurchase",
                    ),
                ),
            ],
            options={
                "db_table": "raw_material_inventory",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RawMaterialIssuance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("job_no", models.CharField(blank=True, max_length=128, null=True)),
                ("issued_carat", models.DecimalField(decimal_places=3, max_digits=12)),
                ("date", models.DateField()),
                ("purpose", models.TextField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_material_issuances",
                        to="core.company",
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issuances",
                        to="vouchers.rawmaterialinventory",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raw_material_issuances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raw_material_issuances",
                        to="vouchers.order",
                    ),
                ),
            ],
            options={
                "db_table": "raw_material_issuances",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyBookClose",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField()),
                ("is_closed", models.BooleanField(default=False)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("total_purchases", models.IntegerField(default=0)),
                ("total_issuances", models.IntegerField(default=0)),
                (
                    "total_purchase_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("total_tasks_completed", models.IntegerField(default=0)),
                ("total_orders", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_book_closes",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "daily_book_closes",
                "ordering": ["-date"],
                "unique_together": {("company", "date")},
            },
        ),
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField()),
                ("tasks_completed", models.IntegerField(default=0)),
                ("tasks_pending", models.IntegerField(default=0)),
                ("orders_processed", models.IntegerField(default=0)),
                ("materials_issued", models.IntegerField(default=0)),
                ("summary", models.TextField(blank=True, null=True)),
                ("challenges", models.TextField(blank=True, null=True)),
                ("next_day_plan", models.TextField(blank=True, null=True)),
                ("is_submitted", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reports",
                        to="core.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "daily_reports",
                "ordering": ["-date", "user__name"],
                "unique_together": {("company", "date", "user")},
            },
        ),
    ]
