# Generated by Django 5.2.7 on 2026-01-10 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_add_master_data_management"),
        ("vouchers", "0027_rawmaterialinventory_rawmaterialissuance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawmaterialpurchase",
            name="material_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of material: Diamond, Gemstone, Metal, etc.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="raw_material_purchases",
                to="core.metaltypemaster",
            ),
        ),
    ]
