# Generated by Django 5.2.7 on 2026-01-10 14:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_add_item_group_master"),
        ("vouchers", "0029_add_three_d_design_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GhatApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "account_order_id",
                    models.CharField(
                        blank=True,
                        help_text="Account & Order ID matching database records",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "ghat_approval",
                    models.BooleanField(
                        default=False, help_text="Yes/No checkbox for ghat approval"
                    ),
                ),
                (
                    "carry_forward_image",
                    models.ImageField(
                        blank=True,
                        help_text="Carry-Forward Image",
                        null=True,
                        upload_to="ghat_approvals/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ghat_approvals",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ghat_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Validated order reference",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ghat_approvals",
                        to="vouchers.order",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_ghat_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ghat_approvals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThreeDPrintingCAM",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "account_order_id",
                    models.CharField(
                        blank=True,
                        help_text="Account & Order ID matching database records",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "cam_piece_image",
                    models.ImageField(
                        blank=True,
                        help_text="CAM Piece Image",
                        null=True,
                        upload_to="3d_printing_cam/",
                    ),
                ),
                (
                    "cam_piece_quality_check",
                    models.BooleanField(
                        default=False, help_text="Yes/No checkbox for quality check"
                    ),
                ),
                (
                    "qc_failure_reasons",
                    models.TextField(
                        blank=True, help_text="List of reasons if quality check fails", null=True
                    ),
                ),
                (
                    "approved_cam_piece",
                    models.ImageField(
                        blank=True,
                        help_text="Approved CAM Piece Image",
                        null=True,
                        upload_to="3d_printing_cam/approved/",
                    ),
                ),
                (
                    "carry_forward_image",
                    models.ImageField(
                        blank=True,
                        help_text="Carry-Forward Image",
                        null=True,
                        upload_to="3d_printing_cam/carry_forward/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="three_d_printing_cam",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_three_d_printing_cam",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Validated order reference",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="three_d_printing_cam_records",
                        to="vouchers.order",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_three_d_printing_cam",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "three_d_printing_cam",
                "ordering": ["-created_at"],
            },
        ),
    ]
