# Generated by Django 5.2.7 on 2026-01-10 15:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_add_item_group_master"),
        ("vouchers", "0030_add_3d_printing_cam_and_ghat_approval"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GhatQualityCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "account_order_id",
                    models.CharField(
                        blank=True,
                        help_text="Account & Order ID matching database records",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "carry_forward_image",
                    models.ImageField(
                        blank=True,
                        help_text="Carry-Forward Image",
                        null=True,
                        upload_to="ghat_quality_checks/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ghat_quality_checks",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ghat_quality_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Validated order reference",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ghat_quality_checks",
                        to="vouchers.order",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_ghat_quality_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ghat_quality_checks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoneDemandToBagging",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "account_order_id",
                    models.CharField(
                        blank=True,
                        help_text="Account & Order ID matching database records",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "measurement_details",
                    models.JSONField(
                        blank=True,
                        help_text="Multiple measurement details with columns, types, and details",
                        null=True,
                    ),
                ),
                (
                    "sent",
                    models.JSONField(
                        blank=True,
                        help_text="Multiple sent records with pieces, total CT, and weight",
                        null=True,
                    ),
                ),
                (
                    "total",
                    models.JSONField(
                        blank=True,
                        help_text="Multiple total records with pieces, total CT, and weight",
                        null=True,
                    ),
                ),
                (
                    "approved_bagging_list",
                    models.ImageField(
                        blank=True,
                        help_text="Approved Bagging List Image",
                        null=True,
                        upload_to="stone_demand_bagging/",
                    ),
                ),
                (
                    "carry_forward_image",
                    models.ImageField(
                        blank=True,
                        help_text="Carry-Forward Image",
                        null=True,
                        upload_to="stone_demand_bagging/carry_forward/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stone_demand_to_bagging",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_stone_demand_to_bagging",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Validated order reference",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stone_demand_to_bagging",
                        to="vouchers.order",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_stone_demand_to_bagging",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stone_demand_to_bagging",
                "ordering": ["-created_at"],
            },
        ),
    ]
