# Generated by Django 5.2.7 on 2026-01-16 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_queries", "0011_salesquery_advance_amount_salesquery_sale_notes"),
        ("vouchers", "0035_add_bagging_diamond_gemstone"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimatevoucher",
            name="sales_query",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estimates",
                to="sales_queries.salesquery",
            ),
        ),
        migrations.AddField(
            model_name="estimatevoucher",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent to Customer"),
                    ("selected", "Selected"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stonedemandtobagging",
            name="measurement_details",
            field=models.JSONField(
                blank=True, help_text="Legacy: Multiple measurement details", null=True
            ),
        ),
        migrations.AlterField(
            model_name="stonedemandtobagging",
            name="sent",
            field=models.JSONField(
                blank=True, help_text="Legacy: Multiple sent records", null=True
            ),
        ),
        migrations.AlterField(
            model_name="stonedemandtobagging",
            name="total",
            field=models.JSONField(
                blank=True, help_text="Legacy: Multiple total records", null=True
            ),
        ),
    ]
