# Generated by Django 5.2.7 on 2026-01-16 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0036_add_sales_query_to_estimate"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimatevoucher",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estimates",
                to="vouchers.sale",
            ),
        ),
    ]
