# Generated by Django 5.2.7 on 2026-01-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0039_add_customer_details_to_estimate"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimatevoucher",
            name="jewellery_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="estimatevoucher",
            name="size_details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
