# Generated by Django 5.2.7 on 2026-01-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0040_estimatevoucher_jewellery_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estimatevoucher",
            name="grand_total",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="estimatevoucher",
            name="gst_amount",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="estimatevoucher",
            name="total_taxable_value",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
