# Generated by Django 5.2.7 on 2026-01-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0041_alter_estimatevoucher_grand_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimatevoucher",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="estimatevoucher",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent to Customer"),
                    ("selected", "Selected"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
