# Generated by Django 5.2.7 on 2026-01-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0042_estimatevoucher_is_archived_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimatevoucher",
            name="product_image",
            field=models.ImageField(
                blank=True,
                help_text="Product image for the estimate",
                null=True,
                upload_to="estimate_images/",
            ),
        ),
    ]
