# Generated by Django 5.2.7 on 2026-01-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0045_add_enhanced_raw_material_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawmaterialpurchase",
            name="additional_details",
            field=models.TextField(blank=True, help_text="Additional details", null=True),
        ),
        migrations.AddField(
            model_name="rawmaterialpurchase",
            name="carat_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Carat weight",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rawmaterialpurchase",
            name="gemstone_type",
            field=models.CharField(
                blank=True, help_text="Type of gemstone", max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="rawmaterialpurchase",
            name="master_size",
            field=models.CharField(
                blank=True, help_text="Master size details", max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="rawmaterialpurchase",
            name="number_of_pieces",
            field=models.IntegerField(blank=True, help_text="Number of pieces", null=True),
        ),
        migrations.AddField(
            model_name="rawmaterialpurchase",
            name="origin",
            field=models.CharField(
                blank=True, help_text="Origin of material", max_length=128, null=True
            ),
        ),
    ]
