# Generated by Django 5.2.7 on 2026-01-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0046_rawmaterialpurchase_additional_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawmaterialpurchase",
            name="color_additional_info",
            field=models.TextField(
                blank=True,
                help_text="Additional color information beyond D-Z scale",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rawmaterialpurchase",
            name="gemstone_size_mm",
            field=models.CharField(
                blank=True, help_text="Gemstone size in mm", max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="rawmaterialpurchase",
            name="sieve_size",
            field=models.CharField(
                blank=True,
                help_text="Sieve size for diamonds",
                max_length=128,
                null=True,
            ),
        ),
    ]
