# Generated by Django 5.2.7 on 2026-01-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0047_rawmaterialpurchase_color_additional_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawmaterialpurchase",
            name="diamond_additional_details",
            field=models.TextField(
                blank=True, help_text="Additional details for diamonds", null=True
            ),
        ),
        migrations.AddField(
            model_name="rawmaterialpurchase",
            name="diamond_number_of_pieces",
            field=models.IntegerField(
                blank=True,
                help_text="Number of diamond pieces (whole numbers only)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rawmaterialpurchase",
            name="diamond_size",
            field=models.CharField(
                blank=True,
                help_text="Diamond size/sieve size",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rawmaterialpurchase",
            name="purchase_budget_per_carat_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Purchase budget per carat in USD (auto-calculated)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rawmaterialpurchase",
            name="purchase_budget_total_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Purchase budget total in USD (converted from INR)",
                max_digits=14,
                null=True,
            ),
        ),
    ]
