# Generated by Django 5.0.14 on 2026-01-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0048_add_missing_diamond_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawmaterialpurchase",
            name="metal_purity",
            field=models.CharField(
                blank=True,
                help_text="Metal purity details (e.g., 999, 925, 99.9%)",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rawmaterialpurchase",
            name="metal_weight_grams",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Metal weight in grams (unified field)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rawmaterialpurchase",
            name="price_per_gram",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price per gram from live rates",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rawmaterialpurchase",
            name="total_metal_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total metal value (weight × price per gram)",
                max_digits=14,
                null=True,
            ),
        ),
    ]
