# Generated by Django 5.2.7 on 2026-02-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0049_rawmaterialpurchase_metal_purity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("STOCK_JEWELRY", "Stock Jewelry"),
                    ("BESPOKE_NATURAL", "Bespoke Natural Jewelry"),
                    ("BESPOKE_CVD", "Bespoke CVD Jewelry"),
                    ("LOOSE_DIAMONDS", "Loose Diamonds"),
                ],
                default="STOCK_JEWELRY",
                help_text="Order type determines the Order ID prefix (A/B/C/D)",
                max_length=20,
            ),
        ),
    ]
