# Generated by Django 5.2.7 on 2026-02-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0050_add_order_type_and_sequence"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("STOCK_JEWELRY", "Stock Jewelry"),
                            ("BESPOKE_NATURAL", "Bespoke Natural Jewelry"),
                            ("BESPOKE_CVD", "Bespoke CVD Jewelry"),
                            ("LOOSE_DIAMONDS", "Loose Diamonds"),
                        ],
                        help_text="Order type for sequence tracking",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "current_sequence",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current sequence number for this order type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Order Sequence",
                "verbose_name_plural": "Order Sequences",
                "db_table": "order_sequences",
            },
        ),
    ]
