# Generated by Django 5.2.7 on 2026-02-08 08:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_populate_initial_departments"),
        ("vouchers", "0051_add_order_sequence_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_confirmation", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending_confirmation",
                        max_length=50,
                    ),
                ),
                (
                    "advance_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
                ),
                ("advance_notes", models.TextField(blank=True)),
                ("order_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "final_order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_draft",
                        to="vouchers.order",
                    ),
                ),
                (
                    "receipt_voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_drafts",
                        to="vouchers.receipt",
                    ),
                ),
                (
                    "source_sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_drafts",
                        to="vouchers.sale",
                    ),
                ),
            ],
            options={
                "db_table": "order_drafts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderProcessLock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "lock_level",
                    models.CharField(
                        choices=[
                            ("UNLOCKED", "Unlocked"),
                            ("LOCKED_FOR_EDIT", "Locked for Edit"),
                            ("FULLY_LOCKED", "Fully Locked"),
                        ],
                        default="LOCKED_FOR_EDIT",
                        max_length=20,
                    ),
                ),
                ("locked_at", models.DateTimeField(auto_now_add=True)),
                ("courier_dispatched", models.BooleanField(default=False)),
                ("courier_dispatched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "locked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_lock",
                        to="vouchers.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_process_locks",
            },
        ),
        migrations.CreateModel(
            name="OrderProcessStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("step_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("position", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_steps",
                        to="vouchers.order",
                    ),
                ),
                (
                    "order_draft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_steps",
                        to="vouchers.orderdraft",
                    ),
                ),
            ],
            options={
                "db_table": "order_process_steps",
                "ordering": ["position"],
            },
        ),
        migrations.AddIndex(
            model_name="orderdraft",
            index=models.Index(
                fields=["source_sale", "status"], name="order_draft_source__b7e267_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderdraft",
            index=models.Index(fields=["company", "status"], name="order_draft_company_29067c_idx"),
        ),
        migrations.AddIndex(
            model_name="orderprocessstep",
            index=models.Index(
                fields=["order_draft", "position"],
                name="order_proce_order_d_6416b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orderprocessstep",
            index=models.Index(fields=["order", "position"], name="order_proce_order_i_e95575_idx"),
        ),
        migrations.AddIndex(
            model_name="orderprocessstep",
            index=models.Index(fields=["status"], name="order_proce_status_6b1ea9_idx"),
        ),
    ]
