# Generated by Django 5.0.14 on 2026-02-09 14:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_subaccount_options"),
        ("core", "0014_alter_dailygoldrate_gold_22k"),
        ("sales_queries", "0015_processtask_department_and_more"),
        ("vouchers", "0051_add_order_sequence_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="Auto-generated invoice number (e.g., INV000001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(help_text="Date the invoice was issued"),
                ),
                ("due_date", models.DateField(help_text="Payment due date")),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("net_7", "Net 7 Days"),
                            ("net_15", "Net 15 Days"),
                            ("net_30", "Net 30 Days"),
                            ("net_60", "Net 60 Days"),
                            ("net_90", "Net 90 Days"),
                            ("custom", "Custom"),
                        ],
                        default="net_30",
                        max_length=20,
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                (
                    "sub_account",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("pan_gstin", models.CharField(blank=True, max_length=50, null=True)),
                ("item_name", models.CharField(max_length=255)),
                (
                    "jewellery_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("size_details", models.TextField(blank=True, null=True)),
                (
                    "sales_person_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=3.0,
                        help_text="GST rate percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "gst_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Grand total including GST",
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "balance_due",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent to Customer"),
                            ("paid", "Paid"),
                            ("partially_paid", "Partially Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes (not shown on PDF)",
                        null=True,
                    ),
                ),
                (
                    "terms_and_conditions",
                    models.TextField(
                        blank=True,
                        help_text="Terms and conditions shown on invoice",
                        null=True,
                    ),
                ),
                (
                    "product_image",
                    models.ImageField(
                        blank=True,
                        help_text="Product image for the invoice",
                        null=True,
                        upload_to="invoice_images/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="accounts.account",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estimate",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to the estimate used",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="vouchers.estimatevoucher",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to the sale record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="vouchers.sale",
                    ),
                ),
                (
                    "sales_query",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to the original sales query",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="sales_queries.salesquery",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "invoices",
                "ordering": ["-invoice_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("particulars", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("shape", models.CharField(blank=True, max_length=50, null=True)),
                ("colour", models.CharField(blank=True, max_length=50, null=True)),
                ("clarity", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        help_text="Piece count",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Weight of the item",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[("CT", "Carat"), ("GM", "Gram"), ("PC", "Piece")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rate per unit",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount for this line item",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="vouchers.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "invoice_line_items",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoicePayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("bank_transfer", "Bank Transfer"),
                            ("upi", "UPI"),
                            ("card", "Credit/Debit Card"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Cheque number, transaction ID, etc.",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="vouchers.invoice",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "invoice_payments",
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_sequence",
                    models.PositiveIntegerField(
                        default=0, help_text="Current sequence number for invoices"
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        default="INV",
                        help_text="Prefix for invoice numbers (e.g., INV, BILL)",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_sequence",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Sequence",
                "verbose_name_plural": "Invoice Sequences",
                "db_table": "invoice_sequences",
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["invoice_number"], name="invoices_invoice_7778bc_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["invoice_date"], name="invoices_invoice_e14adb_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="invoices_status_07776b_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["company", "invoice_date"], name="invoices_company_c4d98c_idx"
            ),
        ),
    ]
