# Generated by Django 5.2.7 on 2026-02-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0055_make_source_sale_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdraft",
            name="sales_query_id",
            field=models.UUIDField(blank=True, help_text="ID of the source Sales Query", null=True),
        ),
    ]
