# Generated by Django 5.2.7 on 2026-02-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0056_orderdraft_sales_query_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderprocessstep",
            name="reference_id",
            field=models.UUIDField(
                blank=True,
                help_text="ID of the related record (e.g., 3D Design, Receipt)",
                null=True,
            ),
        ),
    ]
