# Generated by Django 5.0.14 on 2026-02-16 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0052_invoice_invoicelineitem_invoicepayment_and_more"),
        ("vouchers", "0057_add_reference_id_to_process_steps"),
    ]

    operations = []
