# Generated by Django 5.2.7 on 2026-04-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0062_add_payment_journal_contra_vouchers_and_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contravoucher',
            name='is_pdc',
        ),
        migrations.RemoveField(
            model_name='journalvoucher',
            name='is_pdc',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='is_pdc',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='is_pdc',
        ),
        
    ]
