# Generated by Django 5.2.7 on 2026-04-27 10:58

import django.db.models.deletion
from django.db import migrations, models


def clear_string_party_values(apps, schema_editor):
    ContraVoucher = apps.get_model("vouchers", "ContraVoucher")
    ContraCreditEntry = apps.get_model("vouchers", "ContraCreditEntry")
    ContraVoucher.objects.all().update(party_name=None)
    ContraCreditEntry.objects.all().update(party=None)


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0069_orderprocessstep_next_step_fields"),
    ]

    operations = [
        migrations.RunPython(clear_string_party_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="contracreditentry",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contra_credit_entries",
                to="accounts.account",
            ),
        ),
        migrations.AlterField(
            model_name="contravoucher",
            name="party_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contra_debit_vouchers",
                to="accounts.account",
            ),
        ),
    ]
