# Generated by Django 5.2.7 on 2026-06-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0073_process_step_image_log_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatevoucher',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimatevoucher',
            name='nsj_representative',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
