# Generated by Django 5.2.7 on 2026-06-10 07:31

from django.db import migrations, models


def update_unit_values(apps, schema_editor):
    """Update old unit values to match new UNIT_CHOICES"""
    EstimateLineItem = apps.get_model('vouchers', 'EstimateLineItem')

    # Update old unit values
    for item in EstimateLineItem.objects.all():
        if item.unit == 'per gram':
            item.unit = 'GM'
            item.save()
        elif item.unit == 'per piece':
            item.unit = 'PC'
            item.save()


def reverse_unit_values(apps, schema_editor):
    """Reverse the unit value changes"""
    EstimateLineItem = apps.get_model('vouchers', 'EstimateLineItem')

    # Revert unit values
    for item in EstimateLineItem.objects.all():
        if item.unit == 'GM':
            item.unit = 'per gram'
            item.save()
        elif item.unit == 'PC':
            item.unit = 'per piece'
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0074_estimatevoucher_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatelineitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('CT', 'Carat'), ('GM', 'Gram'), ('PC', 'Piece')], max_length=10),
        ),
        migrations.RunPython(update_unit_values, reverse_unit_values),
    ]
