# Generated by Django 5.2.7 on 2026-01-06 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0006_acgroupmaster_alter_subaccount_options_acgroup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order_date", models.DateField()),
                ("sales_person", models.CharField(max_length=255)),
                ("vendor", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sub_account",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "client_delivery_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("pan_gstin", models.CharField(blank=True, max_length=50, null=True)),
                ("occasion", models.JSONField(blank=True, default=list)),
                ("required_delivery_date", models.DateField(blank=True, null=True)),
                ("stock_in_deadline", models.DateField(blank=True, null=True)),
                ("purpose", models.JSONField(blank=True, default=list)),
                ("jewellery_type", models.CharField(max_length=255)),
                ("size_details", models.TextField(blank=True, null=True)),
                ("fit_details", models.TextField(blank=True, null=True)),
                ("follow_up_log", models.TextField(blank=True, null=True)),
                ("style_preference", models.JSONField(blank=True, default=list)),
                ("metal_preference", models.JSONField(blank=True, default=list)),
                (
                    "diamond_shape",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "color_clarity",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("origin", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "diamond_budget",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("diamond_priority", models.JSONField(blank=True, default=list)),
                ("sample_details", models.TextField(blank=True, null=True)),
                (
                    "gemstone_preference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gemstone_color_clarity",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gemstone_origin",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("other_details", models.TextField(blank=True, null=True)),
                (
                    "budget_range",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("urgency_level", models.JSONField(blank=True, default=list)),
                ("reference_source", models.JSONField(blank=True, default=list)),
                ("must_have", models.TextField(blank=True, null=True)),
                ("must_avoid", models.TextField(blank=True, null=True)),
                ("special_instructions", models.TextField(blank=True, null=True)),
                ("advance_handling", models.JSONField(blank=True, default=dict)),
                ("department_instructions", models.JSONField(blank=True, default=dict)),
                ("design_delivery", models.JSONField(blank=True, default=dict)),
                ("ledger_entries", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_queries",
                        to="accounts.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sales_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Query",
                "verbose_name_plural": "Sales Queries",
                "db_table": "sales_queries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="sales_queri_created_2206e7_idx"),
                    models.Index(fields=["account"], name="sales_queri_account_99522c_idx"),
                    models.Index(fields=["order_date"], name="sales_queri_order_d_f658d0_idx"),
                ],
            },
        ),
    ]
