# Generated by Django 5.2.7 on 2026-01-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_queries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesquery",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
