# Generated by Django 5.2.7 on 2026-01-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_queries", "0002_salesquery_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesquery",
            name="estimate_calculated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="salesquery",
            name="estimate_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
