# Generated by Django 5.2.7 on 2026-01-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_queries", "0003_salesquery_estimate_calculated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesquery",
            name="follow_up_logs",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="salesquery",
            name="transfer_department",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
