# Generated by Django 5.2.7 on 2026-01-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_queries", "0004_salesquery_follow_up_logs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesquery",
            name="follow_up_logs",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
