# Generated by Django 5.2.7 on 2026-01-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_queries", "0005_auto_20260112_1701"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesquery",
            name="reference_photo",
            field=models.FileField(
                blank=True,
                help_text="Upload reference photo for the sales query",
                null=True,
                upload_to="sales_query_photos/",
            ),
        ),
    ]
