# Generated by Django 5.2.7 on 2026-01-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_queries", "0006_salesquery_reference_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesquery",
            name="pan_gstin",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
