# Generated by Django 5.2.7 on 2026-01-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_queries", "0007_alter_salesquery_pan_gstin"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesquery",
            name="selected_estimate_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesquery",
            name="workflow_status",
            field=models.CharField(
                choices=[
                    ("inquiry_received", "Inquiry Received"),
                    ("estimates_pending", "Estimates Pending"),
                    ("estimates_ready", "Estimates Ready"),
                    ("estimate_selected", "Estimate Selected"),
                    ("converted_to_sale", "Converted to Sale"),
                    ("cancelled", "Cancelled"),
                ],
                default="inquiry_received",
                max_length=30,
            ),
        ),
    ]
