# Generated by Django 5.2.7 on 2026-01-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_queries", "0009_alter_salesquery_workflow_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesquery",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
