# Generated by Django 5.2.7 on 2026-01-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_queries", "0010_salesquery_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesquery",
            name="advance_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Advance amount received when converting to sale",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="salesquery",
            name="sale_notes",
            field=models.TextField(
                blank=True, help_text="Notes added during sale conversion", null=True
            ),
        ),
    ]
