# Generated by Django 5.2.7 on 2026-01-27 11:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales_queries", "0012_add_discount_and_other_charges"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesquery",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="salesquery",
            name="other_charges",
        ),
    ]
