# Generated by Django 5.0.14 on 2026-02-03 17:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_queries", "0013_remove_salesquery_discount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_custom",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this uses custom task ordering",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sales_query",
                    models.OneToOneField(
                        help_text="Sales query this process order belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_order",
                        to="sales_queries.salesquery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Process Order",
                "verbose_name_plural": "Process Orders",
                "db_table": "process_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_name",
                    models.CharField(help_text="Name of the task", max_length=200),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Detailed description of the task"),
                ),
                (
                    "original_position",
                    models.IntegerField(help_text="Original position in default order (1-30)"),
                ),
                (
                    "custom_position",
                    models.IntegerField(help_text="Custom position after reordering (1-30)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("blocked", "Blocked"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        help_text="Current task status",
                        max_length=20,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, help_text="Task due date", null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When task was completed", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Additional notes for this task"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User assigned to this task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_process_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "process_order",
                    models.ForeignKey(
                        help_text="Process order this task belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="sales_queries.processorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Process Task",
                "verbose_name_plural": "Process Tasks",
                "db_table": "process_tasks",
                "ordering": ["custom_position"],
            },
        ),
        migrations.CreateModel(
            name="ProcessDependency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dependency_type",
                    models.CharField(
                        choices=[
                            ("must_complete_before", "Must Complete Before"),
                            ("should_complete_before", "Should Complete Before"),
                            ("blocks", "Blocks"),
                        ],
                        default="must_complete_before",
                        help_text="Type of dependency relationship",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "depends_on_task",
                    models.ForeignKey(
                        help_text="Task that must be completed first",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependent_tasks",
                        to="sales_queries.processtask",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Task that has the dependency",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="sales_queries.processtask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Process Dependency",
                "verbose_name_plural": "Process Dependencies",
                "db_table": "process_dependencies",
            },
        ),
        migrations.AddIndex(
            model_name="processtask",
            index=models.Index(
                fields=["process_order", "custom_position"],
                name="process_tas_process_8bd083_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="processtask",
            index=models.Index(fields=["status"], name="process_tas_status_0a4e28_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="processdependency",
            unique_together={("task", "depends_on_task")},
        ),
    ]
