# Generated by Django 5.0.14 on 2026-02-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_queries", "0014_processorder_processtask_processdependency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processtask",
            name="department",
            field=models.CharField(
                blank=True,
                help_text="Department responsible for this task",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="processtask",
            name="custom_position",
            field=models.IntegerField(help_text="Custom position after reordering (1-29)"),
        ),
        migrations.AlterField(
            model_name="processtask",
            name="original_position",
            field=models.IntegerField(help_text="Original position in default order (1-29)"),
        ),
    ]
