# Generated by Django 5.2.7 on 2026-02-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_queries", "0015_processtask_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesquery",
            name="client_delivery_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HOME", "Home Delivery"),
                    ("PICKUP", "Pickup"),
                    ("INSTORE", "In-Store"),
                ],
                help_text="Delivery type: Home, Pickup, or In-Store",
                max_length=20,
                null=True,
            ),
        ),
    ]
