# Generated by Django 5.0.14 on 2026-02-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_queries", "0015_processtask_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesquery",
            name="pan_gstin",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
