# Generated by Django 5.2.7 on 2026-02-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_queries", "0016_add_delivery_type_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesquery",
            name="workflow_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("inquiry_received", "Inquiry Received"),
                    ("estimates_pending", "Estimates Pending"),
                    ("estimates_ready", "Estimates Ready"),
                    ("estimate_selected", "Estimate Selected"),
                    ("converted_to_sale", "Converted to Sale"),
                    ("converted_to_order", "Converted to Order"),
                    ("cancelled", "Cancelled"),
                ],
                default="inquiry_received",
                max_length=30,
                null=True,
            ),
        ),
    ]
