# Generated by Django 5.2.7 on 2026-02-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_queries", "0017_add_converted_to_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesquery",
            name="final_order_id",
            field=models.UUIDField(
                blank=True,
                help_text="ID of the final Order created from this Sales Query",
                null=True,
            ),
        ),
    ]
