# Generated by Django 5.0.14 on 2026-02-16 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales_queries", "0016_alter_salesquery_pan_gstin"),
        ("sales_queries", "0018_salesquery_final_order_id"),
    ]

    operations = []
