# Generated by Django 5.2.7 on 2025-11-03 18:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartyRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("metal_type", models.TextField()),
                ("karat", models.TextField(blank=True, null=True)),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("PER_GRAM", "Per Gram"),
                            ("PERCENT", "Percent"),
                            ("FIXED", "Fixed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rate_value",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "party_rate",
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="DailyRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("rate_date", models.DateField()),
                ("metal_type", models.TextField()),
                ("karat", models.TextField(blank=True, null=True)),
                (
                    "rate_per_gram",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_rates",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "daily_rate",
                "ordering": ["-rate_date"],
            },
        ),
    ]
