# Generated by Django 5.2.7 on 2025-12-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_add_sub_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completion_notes",
            field=models.TextField(
                blank=True, help_text="Notes from assignee about task completion"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="completion_proof",
            field=models.FileField(
                blank=True,
                help_text="File/image uploaded by assignee as proof of completion",
                null=True,
                upload_to="task_completion_proofs/",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="requires_completion_proof",
            field=models.BooleanField(
                default=False,
                help_text="If true, assignee must upload proof before marking complete",
            ),
        ),
    ]
