# Generated by Django 5.2.7 on 2026-01-20 08:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_add_multiple_assignees"),
        ("tasks", "0005_add_completion_proof_fields"),
    ]

    operations = []
