# Generated by Django 5.2.7 on 2026-01-27 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_merge_20260120_1429"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assigned_to_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="assignees",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_tasks_multiple",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="completion_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="completion_proof",
            field=models.FileField(blank=True, null=True, upload_to="task_completion_proofs/"),
        ),
        migrations.AlterField(
            model_name="task",
            name="requires_completion_proof",
            field=models.BooleanField(default=False),
        ),
    ]
