# Generated by Django 5.2.7 on 2025-12-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRODUCT_DESIGN", "Product Design"),
                    ("SALES", "Sales"),
                    ("SOURCING", "Sourcing"),
                    ("FOUNDER", "Founder"),
                    ("ACCOUNTS", "Accounts"),
                    ("RAW_MATERIAL_INVENTORY", "Raw Material Inventory"),
                    ("ADMINISTRATION", "Administration"),
                    ("PRODUCTION", "Production"),
                    ("PRODUCT_INVENTORY", "Product Inventory"),
                    ("LOGISTICS", "Logistics"),
                ],
                help_text="Department the user belongs to",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sub_department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2D_DESIGN", "2D Design"),
                    ("R_AND_D", "R&D"),
                    ("CLIENT_SERVICING", "Client Servicing"),
                    ("CATALOGUE", "Catalogue"),
                    ("DIAMOND_SOURCING", "Diamond Sourcing"),
                    ("GOLD_SOURCING", "Gold Sourcing"),
                    ("GEMSTONE_SOURCING", "Gemstone Sourcing"),
                    ("STRATEGY", "Strategy"),
                    ("OPERATIONS", "Operations"),
                    ("INTEGRATION", "Integration"),
                    ("TECH_INFRA", "Tech Infra"),
                    ("HIRING", "Hiring"),
                    ("LEGAL", "Legal"),
                    ("BRANDING_PR", "Branding & PR"),
                    ("GRAPHIC_DESIGN", "Graphic Design"),
                    ("BUSINESS_DEVELOPMENT", "Business Development"),
                    ("OFFLINE_MARKETING", "Offline Marketing"),
                    ("BILLING", "Billing"),
                    ("GST", "GST"),
                    ("BOOKKEEPING", "Bookkeeping"),
                    ("CASH_BOOKS", "Cash Books"),
                    ("DIAMOND_BOOKS", "Diamond Books"),
                    ("GOLD_BOOKS", "Gold Books"),
                    ("DAILY_IN_OUT", "Daily In Out"),
                    ("BAGGING", "Bagging"),
                    ("ERP", "ERP"),
                    ("PHYSICAL_STOCK_KEEPING", "Physical Stock Keeping"),
                    ("VENDOR_HANDLING", "Vendor Handling"),
                    ("REPAIRS", "Repairs"),
                    ("STOCK_JEWELLERY", "Stock Jewellery"),
                    ("CUSTOM_JEWELLERY", "Custom Jewellery"),
                    ("LOCAL", "Local"),
                    ("SHIPPING", "Shipping"),
                ],
                help_text="Sub-department the user belongs to",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="task_role",
            field=models.CharField(
                choices=[
                    ("FOUNDER", "Founder"),
                    ("DEPT_HEAD", "Department Head"),
                    ("SUB_DEPT_HEAD", "Sub-Department Head"),
                    ("INDIVIDUAL", "Individual Contributor"),
                ],
                default="INDIVIDUAL",
                help_text="Role for task management access control",
                max_length=20,
            ),
        ),
    ]
