# Generated by Django 5.0.14 on 2026-02-01 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_add_department_models"),
        ("users", "0002_add_task_role_and_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_active_department",
            field=models.ForeignKey(
                blank=True,
                help_text="Currently selected department view",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_users",
                to="core.department",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="departments",
            field=models.ManyToManyField(
                blank=True,
                help_text="Departments this user can access (for dashboard switching)",
                related_name="assigned_users",
                to="core.department",
            ),
        ),
    ]
